import type { Metadata } from "next";
import "./globals.css";
import LeftBar from "./components/LeftBar";
import RightBar from "./components/RightBar";
import SessionProvider from "./provider/SessionProvider";
import { Montserrat } from "next/font/google";
import { getServerSession } from "next-auth";
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <div className="grid grid-cols-12  bg-[#0E0C17] h-screen w-screen ">
          <SessionProvider session={session}>
            <LeftBar />
            {children}
            <RightBar />
          </SessionProvider>
        </div>
      </body>
    </html>
  );
}
