import type { Metadata } from "next";
import "./globals.css";
import LeftBar from "./components/LeftBar";
import RightBar from "./components/RightBar";

// Fonts
import { Montserrat } from "next/font/google";
import { Navbar } from "@/components/component/navbar";
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Navbar/>
        <div className="grid grid-cols-12  bg-[#0E0C17] h-screen w-screen ">
          <LeftBar />
          {children}
          <RightBar />
        </div>
      </body>
    </html>
  );
}
